# DataSource property ??
spring.datasource.url=jdbc:mysql://mysql:3306/ssafitdb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=fhqjxmtms26!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource

# MyBatis property ??
mybatis.mapper-locations=mappers/**/*Mapper.xml
mybatis.type-aliases-package=com.example.ssafit.model.dto
mybatis.configuration.map-underscore-to-camel-case=true

spring.sql.init.mode=embedded
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.continue-on-error=true

# view resolver (??? ????)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Swagger property
springdoc.packages-to-scan=com.example.ssafit.controller
springdoc.default-consumes-media-type=application/json;charset=UTF-8
springdoc.default-produces-media-type=application/json;charset=UTF-8
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha

# redis server ??? ?? host ??
spring.data.redis.host=redis
spring.data.redis.port=6379

# jwt ??? secret key
jwt.secret=${JWT_SECRET}
jwt.get.token.uri=/authenticate

# cloud-vision
gcp.vision.key-path=${GCP_CREDENTIALS_PATH}

# chatGPT
openai.api.key=${openapi_keys}
openai.api.url=https://api.openai.com/v1/chat/completions
